/* ***************************************************************************
 * <auto-generated>
 *     This code was generated by a tool.
 *     .NET CLR Runtime Version:4.0.30319.42000
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ***************************************************************************
 * FRXS(ISC) zhangliang4629@163.com 2016/07/27 10:41:11.933
 * **************************************************************************/
using System;

namespace Frxs.ServiceCenter.DataSync.Message.ConsumerClient.EventArgs
{
    /// <summary>
    /// 商品规格创建(Created)事件
    /// 备注：在规格（Attribute）中的使用
    /// 使用范围：规格（Attribute）新增操作中使用
    /// </summary>
    [Serializable]
    public class AttributeCreatedEventAgrs : EventArgsBase
    {
        /// <summary>
        /// 商品规格编号
        /// </summary>
        public int AttributeId { get; set; }
    }
}
