/* ***************************************************************************
 * <auto-generated>
 *     This code was generated by a tool.
 *     .NET CLR Runtime Version:4.0.30319.42000
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ***************************************************************************
 * FRXS(ISC) zhangliang4629@163.com 2016/07/27 10:41:11.951
 * **************************************************************************/
using System;

namespace Frxs.ServiceCenter.DataSync.Message.ConsumerClient.EventArgs
{
    /// <summary>
    /// 运营分类变更(Changed)事件
    /// 备注：在  运营分类（ShopCategory）中的使用
    /// 使用范围：运营分类（ShopCategory）编辑 操作中使用
    /// </summary>
    [Serializable]
    public class ShopCategoryChangedEventAgrs : EventArgsBase
    {
        /// <summary>
        /// 运营分类编号
        /// </summary>
        public int CategoryId { get; set; }
    }
}
