/* ***************************************************************************
 * <auto-generated>
 *     This code was generated by a tool.
 *     .NET CLR Runtime Version:4.0.30319.42000
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ***************************************************************************
 * FRXS(ISC) zhangliang4629@163.com 2016/07/27 10:41:11.968
 * **************************************************************************/
using System;

namespace Frxs.ServiceCenter.DataSync.Message.ConsumerClient.EventArgs
{
    /// <summary>
    /// 供应商移除(Remove)事件
    /// </summary>
    [Serializable]
    public class VendorRemovedEventAgrs : EventArgsBase
    {
        /// <summary>
        /// 供应商编号
        /// </summary>
        public int VendorID { get; set; }
    }
}
