/* ***************************************************************************
 * <auto-generated>
 *     This code was generated by a tool.
 *     .NET CLR Runtime Version:4.0.30319.42000
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ***************************************************************************
 * FRXS(ISC) zhangliang4629@163.com 2016/07/27 10:41:11.977
 * **************************************************************************/
using System;

namespace Frxs.ServiceCenter.DataSync.Message.ConsumerClient.EventArgs
{
    /// <summary>
    /// 仓库移除(Removed)事件
    /// </summary>
    [Serializable]
    public class WarehouseRemovedEventAgrs : EventArgsBase
    {
        /// <summary>
        /// 仓库编号
        /// </summary>
        public int WID { get; set; }
    }
}
