//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frxs.ServiceCenter.DataSync.Message.Server.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Frxs.ServiceCenter.DataSync.Message.Server.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除消息基类存储介质[{0}]成功，删除消息数：{1}，删除时间节点：{2}.
        /// </summary>
        internal static string ClearExpiredMessageTask_DeleteMessage {
            get {
                return ResourceManager.GetString("ClearExpiredMessageTask_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在相同的事件与Topic消息体映射.
        /// </summary>
        internal static string DefaultEvenSelector_Topic_Existsed {
            get {
                return ResourceManager.GetString("DefaultEvenSelector_Topic_Existsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型 {0} 必须继承自 {1}.
        /// </summary>
        internal static string EventArgsTypeAttribute_ERR {
            get {
                return ResourceManager.GetString("EventArgsTypeAttribute_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到对应的消息体映射类型.
        /// </summary>
        internal static string MessagePublisherAction_NotFindBodyType {
            get {
                return ResourceManager.GetString("MessagePublisherAction_NotFindBodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发布消息失败.
        /// </summary>
        internal static string MessagePublisherAction_PublishError {
            get {
                return ResourceManager.GetString("MessagePublisherAction_PublishError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仓库：{0} 未在消息中心注册，请先注册.
        /// </summary>
        internal static string MessagePublisherAction_WID_Not_Reg {
            get {
                return ResourceManager.GetString("MessagePublisherAction_WID_Not_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化数据库成功.
        /// </summary>
        internal static string StartUp_CreatedDB {
            get {
                return ResourceManager.GetString("StartUp_CreatedDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装消息队列{0}成功.
        /// </summary>
        internal static string StartUp_CreatedMSMQ {
            get {
                return ResourceManager.GetString("StartUp_CreatedMSMQ", resourceCulture);
            }
        }
    }
}
