/* ***************************************************************************
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:4.0.30319.42000
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ***************************************************************************
 * FRXS(ISC) zhangliang4629@163.com 2016/07/26 16:56:25.925
 * **************************************************************************/
using System;
using Frxs.ServiceCenter.Api.Core;
using Frxs.ServiceCenter.Data.Core;
using System.Collections.Generic;
using System.Linq;

namespace Frxs.ServiceCenter.DataSync.Message.ApiHost.DataBase.Actions
{
    /// <summary>
    /// 同步接口 - 数据表：ProductsAttributesPicture
    /// </summary>
    [ActionName("ProductsAttributesPicture.Get")]
    public class ProductsAttributesPictureGetAction : 
       ActionBase<ProductsAttributesPictureGetAction.ProductsAttributesPictureGetActionRequestDto, Models.ProductsAttributesPicture>
    {
        /// <summary>
        /// 上送的参数对象
        /// </summary>
        public class ProductsAttributesPictureGetActionRequestDto : RequestDtoBase
        {
            /// <summary>
            /// SqlServer.int
            /// </summary>
            public Int32 ProductId { get; set; }
            
            /// <summary>
            /// 自定义校验上送参数是否正确
            /// </summary>
            /// <returns></returns>
            public override IEnumerable<RequestDtoValidatorResultError> Valid()
            {
                return base.Valid();
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        private readonly IRepository<Models.ProductsAttributesPicture> _productsAttributesPictureRepository;
        private readonly IDbContext _dbContext;
        
        /// <summary>
        /// 构造函数注入需要的参数
        /// </summary>
        /// <param name="productsAttributesPictureRepository">数据访问仓储</param>
        /// <param name="dbContext">数据操作上下文</param>
        public ProductsAttributesPictureGetAction(
            IRepository<Models.ProductsAttributesPicture> productsAttributesPictureRepository,
            IDbContext dbContext)
        {
            this._productsAttributesPictureRepository = productsAttributesPictureRepository;
            this._dbContext = dbContext;
        }

        /// <summary>
        /// 执行业务逻辑
        /// </summary>
        /// <returns></returns>
        public override ActionResult<Models.ProductsAttributesPicture> Execute()
        {
            return this.SuccessActionResult(this._productsAttributesPictureRepository.TableNoTracking
                            .FirstOrDefault(o => o.ProductId == this.RequestDto.ProductId));
        }
    }

    /// <summary>
    /// 同步接口 - 数据表：ProductsAttributesPicture
    /// </summary>
    [ActionName("ProductsAttributesPicture.Get.List")]
    public class ProductsAttributesPictureGetListAction : 
       ActionBase<ProductsAttributesPictureGetListAction.ProductsAttributesPictureGetActionRequestDto, PagedList<Models.ProductsAttributesPicture>>
    {
        /// <summary>
        /// 上送的参数对象
        /// </summary>
        public class ProductsAttributesPictureGetActionRequestDto : RequestDtoBase
        {
            /// <summary>
            /// 页码大小，默认100
            /// </summary>
            public int PageSize { get; set; }

            /// <summary>
            /// 当前页，注意：从0开始
            /// </summary>
            public int PageIndex { get; set; }

            /// <summary>
            /// 总记录数，第一次访问不需要传，第二次回送，提高检索速度
            /// </summary>
            public int TotalCount { get; set; }

            /// <summary>
            /// 
            /// </summary>
            public override void BeforeValid()
            {
                if (this.PageSize <= 0)
                {
                    this.PageSize = 100;
                }
                if (this.PageIndex < 0)
                {
                    this.PageIndex = 0;
                }
                base.BeforeValid();
            }

            /// <summary>
            /// 自定义校验上送参数是否正确
            /// </summary>
            /// <returns></returns>
            public override IEnumerable<RequestDtoValidatorResultError> Valid()
            {
                return base.Valid();
            }
        }

        /// <summary>
        /// 
        /// </summary>
        private readonly IRepository<Models.ProductsAttributesPicture> _productsAttributesPictureRepository;
        private readonly IDbContext _dbContext;

        /// <summary>
        /// 构造函数注入需要的参数
        /// </summary>
        /// <param name="productsAttributesPictureRepository">数据访问仓储</param>
        /// <param name="dbContext">数据操作上下文</param>
        public ProductsAttributesPictureGetListAction(
            IRepository<Models.ProductsAttributesPicture> productsAttributesPictureRepository,
            IDbContext dbContext)
        {
            this._productsAttributesPictureRepository = productsAttributesPictureRepository;
            this._dbContext = dbContext;
        }

        /// <summary>
        /// 执行业务逻辑
        /// </summary>
        /// <returns></returns>
        public override ActionResult<PagedList<Models.ProductsAttributesPicture>> Execute()
        {
            //查询 ProductsAttributesPicture 表数据
            var query = this._productsAttributesPictureRepository.TableNoTracking;

            //根据主键排序
            query = query.OrderBy(o => o.ProductId);

            //获取分页对象
            var pagedList = new ServiceCenter.Data.Core.PagedList<Models.ProductsAttributesPicture>(query,
                this.RequestDto.PageIndex,
                this.RequestDto.PageSize,
                this.RequestDto.TotalCount);

            //返回列表数据
            return this.SuccessActionResult(new PagedList<Models.ProductsAttributesPicture>()
            {
                PageIndex = pagedList.PageIndex,
                PageSize = pagedList.PageSize,
                TotalCount = pagedList.TotalCount,
                TotalPages = pagedList.TotalPages,
                Items = pagedList.ToList()
            });
        }
    }
}
