/* ***************************************************************************
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:4.0.30319.42000
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ***************************************************************************
 * FRXS(ISC) zhangliang4629@163.com 2016/07/26 16:56:25.941
 * **************************************************************************/
using System;
using Frxs.ServiceCenter.Api.Core;
using Frxs.ServiceCenter.Data.Core;
using System.Collections.Generic;
using System.Linq;

namespace Frxs.ServiceCenter.DataSync.Message.ApiHost.DataBase.Actions
{
    /// <summary>
    /// 同步接口 - 数据表：WarehouseEmp
    /// </summary>
    [ActionName("WarehouseEmp.Get")]
    public class WarehouseEmpGetAction : 
       ActionBase<WarehouseEmpGetAction.WarehouseEmpGetActionRequestDto, Models.WarehouseEmp>
    {
        /// <summary>
        /// 上送的参数对象
        /// </summary>
        public class WarehouseEmpGetActionRequestDto : RequestDtoBase
        {
            /// <summary>
            /// SqlServer.int
            /// </summary>
            public Int32 EmpID { get; set; }
            
            /// <summary>
            /// 自定义校验上送参数是否正确
            /// </summary>
            /// <returns></returns>
            public override IEnumerable<RequestDtoValidatorResultError> Valid()
            {
                return base.Valid();
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        private readonly IRepository<Models.WarehouseEmp> _warehouseEmpRepository;
        private readonly IDbContext _dbContext;
        
        /// <summary>
        /// 构造函数注入需要的参数
        /// </summary>
        /// <param name="warehouseEmpRepository">数据访问仓储</param>
        /// <param name="dbContext">数据操作上下文</param>
        public WarehouseEmpGetAction(
            IRepository<Models.WarehouseEmp> warehouseEmpRepository,
            IDbContext dbContext)
        {
            this._warehouseEmpRepository = warehouseEmpRepository;
            this._dbContext = dbContext;
        }

        /// <summary>
        /// 执行业务逻辑
        /// </summary>
        /// <returns></returns>
        public override ActionResult<Models.WarehouseEmp> Execute()
        {
            return this.SuccessActionResult(this._warehouseEmpRepository.TableNoTracking
                            .FirstOrDefault(o => o.EmpID == this.RequestDto.EmpID));
        }
    }

    /// <summary>
    /// 同步接口 - 数据表：WarehouseEmp
    /// </summary>
    [ActionName("WarehouseEmp.Get.List")]
    public class WarehouseEmpGetListAction : 
       ActionBase<WarehouseEmpGetListAction.WarehouseEmpGetActionRequestDto, PagedList<Models.WarehouseEmp>>
    {
        /// <summary>
        /// 上送的参数对象
        /// </summary>
        public class WarehouseEmpGetActionRequestDto : RequestDtoBase
        {
            /// <summary>
            /// 页码大小，默认100
            /// </summary>
            public int PageSize { get; set; }

            /// <summary>
            /// 当前页，注意：从0开始
            /// </summary>
            public int PageIndex { get; set; }

            /// <summary>
            /// 总记录数，第一次访问不需要传，第二次回送，提高检索速度
            /// </summary>
            public int TotalCount { get; set; }

            /// <summary>
            /// 最后修改时间
            /// </summary>
            public DateTime? ModifyTime { get; set; }

            /// <summary>
            /// 仓库编号
            /// </summary>
            public int? WID { get; set; }

            /// <summary>
            /// 
            /// </summary>
            public override void BeforeValid()
            {
                if (this.PageSize <= 0)
                {
                    this.PageSize = 100;
                }
                if (this.PageIndex < 0)
                {
                    this.PageIndex = 0;
                }
                base.BeforeValid();
            }

            /// <summary>
            /// 自定义校验上送参数是否正确
            /// </summary>
            /// <returns></returns>
            public override IEnumerable<RequestDtoValidatorResultError> Valid()
            {
                return base.Valid();
            }
        }

        /// <summary>
        /// 
        /// </summary>
        private readonly IRepository<Models.WarehouseEmp> _warehouseEmpRepository;
        private readonly IDbContext _dbContext;

        /// <summary>
        /// 构造函数注入需要的参数
        /// </summary>
        /// <param name="warehouseEmpRepository">数据访问仓储</param>
        /// <param name="dbContext">数据操作上下文</param>
        public WarehouseEmpGetListAction(
            IRepository<Models.WarehouseEmp> warehouseEmpRepository,
            IDbContext dbContext)
        {
            this._warehouseEmpRepository = warehouseEmpRepository;
            this._dbContext = dbContext;
        }

        /// <summary>
        /// 执行业务逻辑
        /// </summary>
        /// <returns></returns>
        public override ActionResult<PagedList<Models.WarehouseEmp>> Execute()
        {
            //查询 WarehouseEmp 表数据
            var query = this._warehouseEmpRepository.TableNoTracking;

            //仓库编号
            if (this.RequestDto.WID.HasValue)
            {
                query = query.Where(o => o.WID == this.RequestDto.WID.Value); 
            }

            //当前修改时间是否存在
            if (this.RequestDto.ModifyTime.HasValue)
            {
                query = query.Where(o => o.ModifyTime >= this.RequestDto.ModifyTime.Value); 
            }

            //根据主键排序
            query = query.OrderBy(o => o.EmpID);

            //获取分页对象
            var pagedList = new ServiceCenter.Data.Core.PagedList<Models.WarehouseEmp>(query,
                this.RequestDto.PageIndex,
                this.RequestDto.PageSize,
                this.RequestDto.TotalCount);

            //返回列表数据
            return this.SuccessActionResult(new PagedList<Models.WarehouseEmp>()
            {
                PageIndex = pagedList.PageIndex,
                PageSize = pagedList.PageSize,
                TotalCount = pagedList.TotalCount,
                TotalPages = pagedList.TotalPages,
                Items = pagedList.ToList()
            });
        }
    }
}
